# Site settings
title: Background Process
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on technology and other things I'm learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://backgroundprocess.com" # the base hostname & protocol for your site
github_username: tkuhlman

# Build settings
markdown: kramdown
